### ISSUE TITLE
Installation not possible

### ISSUE THREAD

**Issue by CarpeDiemKopi** [joshuafontany/TW5-JsonMangler#8]
These given links are not working:

![image](https://user-images.githubusercontent.com/32836136/65698810-6619a000-e07d-11e9-9127-d9d5d3773fdd.png)

I found the mod-loader plugin, but not the Action-MakeTid plugin.

**Comment by joshuafontany** [comment]
Hello! I did put together that last release in the middle of recovering from an hdd failure. I'll look into it this week, thanks!

Also, I had to reverse engineer some of Evan's work in order to refactor it and make his plugins work with the more recent Tiddlywiki releases (I see you opened some issues over there).

**Comment by CarpeDiemKopi** [comment]
Perhaps this explains the following strange behavior after importing the plugin: 

> **Big link icons on every tab, can't set fluid story.**

(TonyM, [Do you also have problems with the Mod-Loader plugin? Please report](https://groups.google.com/d/msg/tiddlywiki/LaSQeLH351s/ZY1iT2YnBAAJ))

Could that have something to do with this? 
I think the idea behind the plugin is excellent, but I don't want to cause any problems with my plugins.

**Comment by joshuafontany** [comment]
Aaah, I see. The links and instructions in the GitHub ReadMe were broken.

I have updated the ReadMe, and clarified that you have to open the Example Wiki to install the plugin tiddlers directly. Thanks!
